server.port: 9000
spring:
    application:
        name: gateway
    profiles:
        active: query

---
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
            routes:
            - id: service-hello
            uri: lb://SERVICE-HELLO
            predicates:
            - Path=/service/**
            filters:
            - StripPrefix=1
            - RequestTime=true
    profiles: eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# query string路由
spring:
    cloud:
        gateway:
            routes:
            - id: query_route
              uri: http://localhost:8080
              predicates:
              - Query=foo, ba.
    profiles: query

---
# http request header路由
spring:
    cloud:
        gateway:
            routes:
            - id: header_route
              uri: http://localhost:8080
              predicates:
              - Header=X-Request-Id, \d+
    profiles: header

---
# cookie路由
spring:
    cloud:
        gateway:
            routes:
            - id: cookie_route
              uri: http://localhost:8080
              predicates:
              - Cookie=chocolate, ch.p
    profiles: cookie

---
# http method 路由
spring:
    cloud:
        gateway:
            routes:
            - id: method_route
              uri: http://localhost:8080
              predicates:
              - Method=GET
    profiles: method

---
# 远程主机ip地址路由
spring:
    cloud:
        gateway:
            routes:
            - id: remoteaddr_route
              uri: http://localhost:8080
              predicates:
              - RemoteAddr=192.168.0.1/24
    profiles: remoteaddr

---
# hystrix 断路器
spring:
    cloud:
        gateway:
            routes:
            - id: filter_route
              uri: lb://backing-service:8088
              predicates:
              - Path=/hello
              filters:
              - name: Hystrix
                args:
                    name: fallbackcmd
                    fallbackUri: forward:/helloFallback
              - RewritePath=/hello, /hi
              - StripPrefix=1
              - PrefixPath=/service
              - AddRequestHeader=X-Request-Foo, Bar
    profiles: filter
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000










